name: docker-publish

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: BORRAGEIROS-ENV
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: borrageiros/discord-who-joined:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push (arm64)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: borrageiros/discord-who-joined:arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
